import {DateTime} from 'luxon';

export class BaseEntity {
  /**
   * ID of the entity.
   * Autogenerated.
   * This value should remain immutable.
   * @example "0x123456789"
   * @readonly
   **/
  readonly uid?: string;
  ['dgraph.type']: string[];
  // Auditing entries
  createdAt?: DateTime;
  updatedAt?: DateTime;
}
